

services:

  #  MySQL Database
  mysql:
    image: mysql:8.0
    container_name: pems-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pems_db
    ports:
      - "3307:3306"    # Local MySQL se conflict na ho isliye 3307
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pems-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ============ Spring Boot Backend ============
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pems-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pems_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      DB_PASSWORD: rootpassword
      JWT_SECRET: EDdlpE/PSzpWb7zTBfkY+ZhwLOzhGhCxToMCRVRHU8ag15kA3nZ8oumfM/bbxi9aMSrNDYUW2/+FnH7/HC6wTg==
    ports:
      - "8080:8080"
    networks:
      - pems-network

  # ============ React Frontend (Nginx) ============
  frontend:
    build:
      context: ./pems-frontend
      dockerfile: Dockerfile
    container_name: pems-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - pems-network

# ============ Volumes ============
volumes:
  mysql-data:
    driver: local

# ============ Networks ============
networks:
  pems-network:
    driver: bridge