spring.application.name=pems

# MySQL Database Configuration (Docker + Local dono ke liye)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pems_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080